sudo: required
services: 
    - docker

before_install:
    - docker build -t mrbost/docker-react -f Dockerfile.dev .    

    
script:
    - docker run -e CI=true mrbost/docker-react npm run test -- --coverage